#slime spawn buff(runs a random chance for a slime to spawn with a mob)
#slimeChanceEnabled needs to be true for slimeChance to take effect
#default: 0.1(10%)

slimeChanceEnabled : true
slimeChance : 0.1

#quantity of raiders to be added to the raid, default adds 1 raider of the same type per existing raider

raiderQuantity : 1

#zombie iron drop buff
#zombieIronEnabled needs to be true for zombieIron to take effect
#default: 0.1(10%)

zombieIronEnabled : true
zombieIron : 0.1