name: BuffRates-OG
author: Sekalol15
description: Buffs various mob spawn and drop rates.
website: https://github.com/Sekalol15/BuffRates-OG
version: '${version}'
api-version: '${apiVersion}'
main: plugin.BuffRatesOG
